### PR TITLE
Add Rubinius to Build Matrix with Allowed Failure

### PR DESCRIPTION
**Pull request by bjfish**
Adding Rubinius to build matrix to verify that FactoryGirl works on Rubinius. I would appreciate if you could add this to your build matrix so we can ensure FactoryGirl works on Rubinius. Thank you.

### CODE REVIEW

**Comment by joshuaclayton** [comment]
@bjfish I'm fine with supporting RBX, but why the allow-failures flag?

**Comment by bjfish** [comment]
@joshuaclayton I can remove allowed failures. I'll update the PR.

I usually do allow_failures to not interfere with anyones current builds in case of failure.

We have a dashboard here to observe failures: http://bjfish.github.io/rubinius-gem-build-status/page4/

**Comment by joshuaclayton** [comment]
@bjfish thanks again for handling this - can you rebase against master and verify everything looks good on Travis?

**Comment by bjfish** [comment]
@joshuaclayton I rebased and it looks like the build passed.

**Comment by joshuaclayton** [comment]
@bjfish - thanks, merged as ed84cda57ef13999a5fe42c76d07503b6d3962bd

**Pull request closed without merging**
