### PR TITLE
Pass evaluator to to_create

### PR DESCRIPTION
**Pull request by composerinteralia**
Feature request from https://github.com/thoughtbot/factory_girl/issues/1010. I'm happy to rework this if we want to take a different approach.

### CODE REVIEW

**Comment by composerinteralia** [comment]
Thanks, hound! 🐶

**Comment by joshuaclayton** [comment]
Thanks for this @composerinteralia!

**Comment by composerinteralia** [comment]
Thanks for merging @joshuaclayton ! I heard you talk about `factory_girl` in one of the old thoughtbot podcasts, and it got me excited about looking through the source code. It has been a lot of fun! I am going to write a blog post about it. I will send it your way when I finish.

**Comment by joshuaclayton** [comment]
Glad to hear it, and keep me posted when you publish @composerinteralia!

**Pull request merged**
